### ISSUE TITLE
Error with Vanilla SFX Nodes

### ISSUE THREAD

**Issue by sogm8** [theodox/sfx#3]
Hey there.

I'm trying to learn how to use your module for vanilla shaderFX networks, and I'm getting the an error on a print command.

This is the code I'm trying to run:
```
from sfx import SFXNetwork
import sfx.pbsnodes as pbsnodes

network = SFXNetwork.create("new_shader")
print network.nodes
```

Then I get the following error in Maya:
```
Error: nodetype
Traceback (most recent call last):
    File "<maya console>", line 8, in <module>
    File "S:/folder/Maya/scripts\sfx\__init__.py", line 199, in __repr__
        return "<sfxNode '{0}' ({1})>".format(self.name, self.nodetype)
    File "S:/folder/Maya/scripts\sfx\__init__.py", line 173, in __getattr__
        return object.__getattribute__(self, item)
AttributeError: nodetype
```

Thanks for your help.

**Comment by FrandSX** [comment]
Heya,

Seeing the same issue with Maya 2018 / Windows 10.

```
from sfx import SFXNetwork
import sfx.sfxnodes as sfxnodes

network = SFXNetwork.create('new_shader')

print network.nodes
```

Brings up:
```
// Error: nodetype
# Traceback (most recent call last):
#   File "<maya console>", line 6, in <module>
#   File "C:/Users/frand/Documents/maya/scripts\sfx\__init__.py", line 199, in __repr__
#     return "<sfxNode '{0}' ({1})>".format(self.name, self.nodetype)
#   File "C:/Users/frand/Documents/maya/scripts\sfx\__init__.py", line 173, in __getattr__
#     return object.__getattribute__(self, item)
# AttributeError: nodetype //
```
